from src.models.context import SessionContext, TrackedEntity, EntityType, EntityPriority
from src.models.plan import ExecutionPlan
from src.utils.logger import get_logger

logger = get_logger("context.entity_tracker")

class EntityTracker:
    """Extracts structured entities from execution plans and updates the active context scopes."""
    
    @staticmethod
    def extract_from_plan(plan: ExecutionPlan, context: SessionContext) -> None:
        """
        Inspects the tools generated by the LLM Planner to detect OS and Browser automation entities.
        Since this reads the structured JSON tool payload, it is 100% accurate as a source of truth.
        """
        if not plan.plan:
            return
            
        for tool_call in plan.plan:
            name = tool_call.tool
            args = tool_call.arguments
            
            # Application Extractor
            if name in ("open_application", "close_application", "focus_application"):
                if "application" in args:
                    entity = TrackedEntity(
                        type=EntityType.APPLICATION, 
                        value=args["application"],
                        priority=EntityPriority.HIGH
                    )
                    context.automation.last_application = entity
                    context.automation.recent_entities.append(entity)
                    logger.debug(f"Tracked Application Entity: {entity.value}")
                    
            # Folder Extractor
            elif name in ("create_folder", "open_folder", "delete_folder"):
                if "name" in args:
                    entity = TrackedEntity(
                        type=EntityType.FOLDER,
                        value=args["name"],
                        priority=EntityPriority.MEDIUM
                    )
                    context.automation.last_folder = entity
                    context.automation.recent_entities.append(entity)
                    logger.debug(f"Tracked Folder Entity: {entity.value}")
                    
            # File Extractor
            elif name in ("create_file", "delete_file", "read_file"):
                if "name" in args:
                    entity = TrackedEntity(
                        type=EntityType.FILE,
                        value=args["name"],
                        priority=EntityPriority.MEDIUM
                    )
                    context.automation.last_file = entity
                    context.automation.recent_entities.append(entity)
                    logger.debug(f"Tracked File Entity: {entity.value}")
                    
            # Website Extractor
            elif name in ("browser_search", "browser_open"):
                if "query" in args:
                    entity = TrackedEntity(
                        type=EntityType.WEBSITE,
                        value=args["query"],
                        priority=EntityPriority.HIGH
                    )
                    context.automation.last_website = entity
                    context.automation.recent_entities.append(entity)
                    logger.debug(f"Tracked Website Entity: {entity.value}")
                    
        # Prune recent automation entities to prevent endless memory bloat
        if len(context.automation.recent_entities) > 10:
            context.automation.recent_entities = context.automation.recent_entities[-10:]

    @staticmethod
    def extract_knowledge_topic(query: str, context: SessionContext) -> None:
        """Extracts and tracks topics discussed during knowledge queries."""
        
        entity = TrackedEntity(
            type=EntityType.TOPIC,
            value=query,
            priority=EntityPriority.MEDIUM
        )
        context.knowledge.current_topic = entity
        context.knowledge.recent_concepts.append(entity)
        logger.debug(f"Tracked Knowledge Topic: {entity.value}")
        
        # Prune knowledge history
        if len(context.knowledge.recent_concepts) > 5:
            context.knowledge.recent_concepts = context.knowledge.recent_concepts[-5:]
