from pydantic import BaseModel, Field

from src.models.error_codes import ErrorCode

class PlanItem(BaseModel):
    """Represents a single step in the execution plan."""
    tool: str = Field(description="The name of the tool to execute.")
    arguments: dict = Field(default_factory=dict, description="Key-value arguments for the tool.")

class ExecutionPlan(BaseModel):
    """Represents the complete sequential plan generated by the LLM."""
    plan: list[PlanItem] = Field(description="Ordered list of plan items to execute.")

class ExecutionContext(BaseModel):
    """Represents the context under which tools are executed."""
    cwd: str = Field(description="The current working directory.")
    os: str = Field(description="The operating system name.")
    user: str = Field(description="The current active user username.")
    time: str = Field(description="The current system time.")
    session_id: str = Field(description="Unique identifier for the current application session.")
    execution_id: str = Field(description="Unique identifier for this specific tool execution pass.")

class ToolResult(BaseModel):
    """Represents the structured result of executing a single tool."""
    tool_name: str = Field(description="The name of the executed tool.")
    success: bool = Field(description="Whether the tool execution succeeded.")
    user_message: str = Field(description="Human-readable execution message safe for TTS.")
    developer_message: str = Field(description="Internal diagnostic message meant for developers and logs.")
    error_code: ErrorCode = Field(default=ErrorCode.NONE, description="Categorical error code for failures.")
    duration: float = Field(description="The duration of execution in seconds.")
    data: dict = Field(default_factory=dict, description="Any data returned by the tool.")
