from typing import List, Optional
from pydantic import BaseModel, Field

from src.models.error_codes import ErrorCode
from src.models.context_scope import AutomationContext, KnowledgeContext, ConversationContext, SystemContext
from src.models.interaction import InteractionContext

class PlanItem(BaseModel):
    """Represents a single step in the execution plan."""
    tool: str = Field(description="The name of the tool to execute.")
    arguments: dict = Field(default_factory=dict, description="Key-value arguments for the tool.")

class ExecutionPlan(BaseModel):
    """Represents the complete sequential plan generated by the LLM."""
    plan: list[PlanItem] = Field(description="Ordered list of plan items to execute.")

class ExecutionContext(BaseModel):
    """Represents the context under which tools are executed."""
    system: SystemContext = Field(default_factory=SystemContext)
    automation: AutomationContext = Field(default_factory=AutomationContext)
    interaction: Optional[InteractionContext] = None
    knowledge: KnowledgeContext = Field(default_factory=KnowledgeContext)
    conversation: ConversationContext = Field(default_factory=ConversationContext)
    history: List[str] = Field(default_factory=list)

class ToolResult(BaseModel):
    """Represents the structured result of executing a single tool."""
    tool_name: str = Field(description="The name of the executed tool.")
    success: bool = Field(description="Whether the tool execution succeeded.")
    user_message: str = Field(description="Human-readable execution message safe for TTS.")
    developer_message: str = Field(description="Internal diagnostic message meant for developers and logs.")
    error_code: ErrorCode = Field(default=ErrorCode.NONE, description="Categorical error code for failures.")
    duration: float = Field(description="The duration of execution in seconds.")
    data: dict = Field(default_factory=dict, description="Any data returned by the tool.")
